services:
  modelo:
    build: ./model
    container_name: Modelo
    ports:
      - "5000:5000"
  gui:
    build: ./gui
    container_name: GUI
    ports:
      - "7860:7860"
    depends_on:
      - modelo