services:
  modelo:
    build: 
      context: ./model
    container_name: Modelo
    ports:
      - "5000:5000"
    networks:
      - red-principal

  gui:
    build: 
      context: ./gui
    container_name: GUI
    ports:
      - "7860:7860"
    networks:
      - red-principal
    depends_on:
      - modelo

networks:
  red-principal:
    driver: bridge