services:
  modelo:
    build: ./App
    container_name: Modelo
    ports:
      - "5000:5000"
  gui:
    build: ./GUI
    container_name: GUI
    ports:
      - "8080:8080"
    depends_on:
      - modelo