services:
  modelo:
    build: 
      context: ./model
    container_name: Modelo
    ports:
      - "5000:5000"
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "512M"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: 3
  gui:
    build: 
      context: ./gui
    container_name: GUI
    ports:
      - "7860:7860"
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "512M"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: 3
    depends_on:
      - modelo
